"""
reporting.py — Professional PDF mix design report using ReportLab.
Teymouri Research Lab | South Dakota State University
"""
from datetime import date
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from src.schemas import MixDesignResult

TEAL        = colors.HexColor("#0F6E56")
TEAL_LIGHT  = colors.HexColor("#E1F5EE")
AMBER       = colors.HexColor("#854F0B")
AMBER_LIGHT = colors.HexColor("#FAEEDA")
RED         = colors.HexColor("#A32D2D")
RED_LIGHT   = colors.HexColor("#FCEBEB")
GRAY_DARK   = colors.HexColor("#444441")
GRAY_MID    = colors.HexColor("#888780")
GRAY_LIGHT  = colors.HexColor("#F1EFE8")
BORDER      = colors.HexColor("#D3D1C7")
SDSU_BLUE   = colors.HexColor("#0033A0")
WHITE       = colors.white
BLACK       = colors.HexColor("#2C2C2A")

def PS(name, size, font="Helvetica", color=None, leading=None, **kw):
    return ParagraphStyle(name, fontSize=size, fontName=font,
                          textColor=color or BLACK,
                          leading=leading or size * 1.4, **kw)

def _val(v): return v if v and v.strip() else "Not provided by user"


def generate_pdf_report(result: MixDesignResult) -> bytes:
    buf = BytesIO()
    W = 7.0 * inch
    inp = result.input_summary
    pi  = inp.project_info
    aci = result.aci_result
    p   = aci["proportions"]
    v   = aci["volumes_ft3"]
    total_scm = inp.flyash_pct + inp.slag_pct + inp.sf_pct + inp.pcc_pct

    doc = SimpleDocTemplate(buf, pagesize=letter,
        leftMargin=0.75*inch, rightMargin=0.75*inch,
        topMargin=0.75*inch, bottomMargin=0.75*inch,
        title="Concrete Mix Design Report — Teymouri Research Lab")

    s_h1   = PS("h1", 18, "Helvetica-Bold", BLACK, spaceAfter=2)
    s_h2   = PS("h2", 10, "Helvetica-Bold", SDSU_BLUE, spaceAfter=1)
    s_sec  = PS("sc", 11, "Helvetica-Bold", TEAL, spaceBefore=10, spaceAfter=5)
    s_body = PS("b",  8.5, color=GRAY_DARK, leading=13, spaceAfter=3)
    s_sm   = PS("sm", 8,   color=GRAY_MID,  leading=12)
    s_bold = PS("bd", 13, "Helvetica-Bold", BLACK, leading=18)
    s_note = PS("nt", 7.5, "Helvetica-Oblique", GRAY_MID, leading=11)
    s_wh   = PS("wh", 8.5, "Helvetica-Bold", WHITE)
    s_demo = PS("dm", 8,   "Helvetica-Oblique", SDSU_BLUE, leading=12)

    story = []

    # ── SDSU / Lab banner ─────────────────────────────────────────────────────
    banner = Table([[
        Paragraph("Teymouri Research Lab", PS("lab", 9, "Helvetica-Bold", WHITE)),
        Paragraph("Dept. of Construction &amp; Concrete Industry Management | Jerome J. Lohr College of Engineering | South Dakota State University",
                  PS("labsub", 7.5, color=WHITE, leading=11)),
    ]], colWidths=[1.8*inch, 5.2*inch])
    banner.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,-1), SDSU_BLUE),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7),
        ("LEFTPADDING",(0,0),(-1,-1),10),
    ]))
    story += [banner, Spacer(1,4)]

    demo_note = Table([[
        Paragraph("DEMO — This report was generated by a prototype tool developed by the Teymouri Research Lab at SDSU. "
                  "For research and educational purposes only.", s_demo)
    ]], colWidths=[W])
    demo_note.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,-1), colors.HexColor("#E6F1FB")),
        ("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5),
        ("LEFTPADDING",(0,0),(-1,-1),10),
        ("LINEBELOW",(0,0),(-1,-1),0.5,SDSU_BLUE),
    ]))
    story += [demo_note, Spacer(1,10)]

    # ── Main header ───────────────────────────────────────────────────────────
    ht = Table([[
        Paragraph("Concrete Mix Design Report", s_h1),
        Paragraph(f"Date: {date.today().strftime('%B %d, %Y')}<br/>Method: ACI 211.1 (PCA Method)", s_sm),
    ]], colWidths=[4.5*inch, 2.5*inch])
    ht.setStyle(TableStyle([
        ("VALIGN",(0,0),(-1,-1),"TOP"), ("ALIGN",(1,0),(1,0),"RIGHT"),
        ("LINEBELOW",(0,0),(-1,0),1.5,TEAL),
        ("BOTTOMPADDING",(0,0),(-1,0),8),
    ]))
    story += [ht, Spacer(1,10)]

    # ── Project info block ────────────────────────────────────────────────────
    story.append(Paragraph("Project information", s_sec))
    proj_rows = [
        ["Project name", _val(pi.project_name), "Location", _val(pi.location)],
        ["Prepared by",  _val(pi.prepared_by),  "Company",  _val(pi.company)],
    ]
    if inp.uploaded_file_name:
        proj_rows.append(["Uploaded file", inp.uploaded_file_name, "", ""])
    pt = Table(proj_rows, colWidths=[1.3*inch, 2.3*inch, 1.1*inch, 2.3*inch])
    pt.setStyle(TableStyle([
        ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"), ("FONTNAME",(2,0),(2,-1),"Helvetica-Bold"),
        ("FONTSIZE",(0,0),(-1,-1),8.5),
        ("TEXTCOLOR",(0,0),(-1,-1),GRAY_DARK),
        ("ROWBACKGROUNDS",(0,0),(-1,-1),[WHITE,GRAY_LIGHT]),
        ("GRID",(0,0),(-1,-1),0.5,BORDER),
        ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
        ("LEFTPADDING",(0,0),(-1,-1),8),
    ]))
    story += [pt, Spacer(1,8)]

    # ── Risk banner ───────────────────────────────────────────────────────────
    risk_map = {"Low":(TEAL_LIGHT,TEAL),"Moderate":(AMBER_LIGHT,AMBER),"High":(RED_LIGHT,RED)}
    bg, fg = risk_map.get(result.risk_level,(AMBER_LIGHT,AMBER))
    rb = Table([[
        Paragraph(f"<b>Risk: {result.risk_level}</b>", PS("rl",10,"Helvetica-Bold",fg)),
        Paragraph(result.ai_analysis or "", PS("rs",8.5,color=fg,leading=13)),
    ]], colWidths=[1.2*inch, 5.8*inch])
    rb.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),bg),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8),
        ("LEFTPADDING",(0,0),(-1,-1),10)]))
    story += [rb, Spacer(1,10)]

    # ── File review note (if file was uploaded) ───────────────────────────────
    if result.file_review_notes:
        story.append(Paragraph("Uploaded file review", s_sec))
        frt = Table([[result.file_review_notes]], colWidths=[W])
        frt.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#E6F1FB")),
            ("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8),
            ("LEFTPADDING",(0,0),(-1,-1),10),("GRID",(0,0),(-1,-1),0.5,BORDER),
            ("FONTSIZE",(0,0),(-1,-1),8.5),("TEXTCOLOR",(0,0),(-1,-1),GRAY_DARK),
        ]))
        story += [frt, Spacer(1,8)]

    # ── Metrics ───────────────────────────────────────────────────────────────
    labels = ["Design f'c","w/cm","Air content","Fresh density","Total volume"]
    values = [f"{aci['design_fc_psi']:,} psi", f"{aci['selected_wcm']:.2f}",
              f"{aci['air_pct']}%", f"{aci['density_pcf']} pcf",
              f"{v['total']:.2f} ft\xb3/CY"]
    mt = Table(
        [[Paragraph(l, s_sm) for l in labels],
         [Paragraph(f"<b>{val}</b>", s_bold) for val in values]],
        colWidths=[W/5]*5)
    mt.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,-1),GRAY_LIGHT),
        ("ALIGN",(0,0),(-1,-1),"CENTER"),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6),
        ("LINEBEFORE",(1,0),(-1,-1),0.5,BORDER),
    ]))
    story += [mt, Spacer(1,12)]

    # ── Inputs + Material producers ───────────────────────────────────────────
    story.append(Paragraph("Mix design inputs", s_sec))
    inp_rows = [
        ["Parameter","Value","SCM","Replacement"],
        ["Required f'c",f"{inp.fc_psi:,} psi","Portland cement",f"{100-total_scm:.0f}%"],
        ["Exposure classes",", ".join(inp.exposure_codes),"Fly ash",f"{inp.flyash_pct:.0f}%"],
        ["Max agg size",f'{inp.agg_size}"',"Slag",f"{inp.slag_pct:.0f}%"],
        ["Target slump",f'{inp.slump}"',"Silica fume",f"{inp.sf_pct:.0f}%"],
        ["Fineness modulus",f"{inp.fm_fa:.2f}","PCC (micro-filler)",f"{inp.pcc_pct:.0f}%"],
        ["SG CA / FA",f"{inp.sg_ca:.2f} / {inp.sg_fa:.2f}","Total SCM",f"{total_scm:.0f}%"],
        ["Rodded density",f"{inp.rodded_density_ca:.0f} lbs/ft\xb3","Air entrained","Yes" if inp.air_entrained else "No"],
        ["Aggregate shape",inp.agg_shape,"",""],
    ]
    it = Table(inp_rows, colWidths=[2.0*inch,1.6*inch,1.6*inch,1.3*inch])
    it.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),TEAL),("TEXTCOLOR",(0,0),(-1,0),WHITE),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
        ("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),("FONTNAME",(2,1),(2,-1),"Helvetica-Bold"),
        ("FONTSIZE",(0,0),(-1,-1),8.5),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[WHITE,GRAY_LIGHT]),
        ("GRID",(0,0),(-1,-1),0.5,BORDER),
        ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
        ("LEFTPADDING",(0,0),(-1,-1),8),
        ("TEXTCOLOR",(0,1),(-1,-1),GRAY_DARK),
        ("LINEAFTER",(1,0),(1,-1),1.0,TEAL),
    ]))
    story += [it, Spacer(1,8)]

    # ── Material producers ────────────────────────────────────────────────────
    story.append(Paragraph("Material producers", s_sec))
    prod_rows = [
        ["Material","Producer / Source"],
        ["Portland cement", _val(pi.cement_producer)],
        ["Fly ash",         _val(pi.flyash_producer)  if inp.flyash_pct > 0 else "N/A — not used"],
        ["Slag",            _val(pi.slag_producer)    if inp.slag_pct > 0   else "N/A — not used"],
        ["Silica fume",     _val(pi.sf_producer)      if inp.sf_pct > 0     else "N/A — not used"],
        ["PCC (micro-filler)", _val(pi.pcc_producer)  if inp.pcc_pct > 0   else "N/A — not used"],
    ]
    prt = Table(prod_rows, colWidths=[2.0*inch, 5.0*inch])
    prt.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),TEAL),("TEXTCOLOR",(0,0),(-1,0),WHITE),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
        ("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),
        ("FONTSIZE",(0,0),(-1,-1),8.5),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[WHITE,GRAY_LIGHT]),
        ("GRID",(0,0),(-1,-1),0.5,BORDER),
        ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
        ("LEFTPADDING",(0,0),(-1,-1),8),
        ("TEXTCOLOR",(0,1),(-1,-1),GRAY_DARK),
    ]))
    story += [prt, Spacer(1,12)]

    # ── Proportions ───────────────────────────────────────────────────────────
    story.append(Paragraph("Mix proportions per cubic yard", s_sec))
    total_mass = sum([p['water_lbs'],p['cement_lbs'],p['flyash_lbs'],
                      p['slag_lbs'],p['sf_lbs'],p['pcc_lbs'],p['ca_lbs'],p['fa_lbs']])
    pr = [["Material","lbs/CY","ft\xb3/CY","Notes"],
          ["Water",f"{p['water_lbs']:.0f}",f"{v['water']:.3f}",f"w/cm = {aci['selected_wcm']:.2f}"],
          ["Portland cement",f"{p['cement_lbs']:.0f}",f"{v['cement']:.3f}",f"{100-total_scm:.0f}% of CM"]]
    if inp.flyash_pct>0: pr.append(["Fly ash",f"{p['flyash_lbs']:.0f}",f"{v['flyash']:.3f}",f"{inp.flyash_pct:.0f}% replacement"])
    if inp.slag_pct>0:   pr.append(["Slag",f"{p['slag_lbs']:.0f}",f"{v['slag']:.3f}",f"{inp.slag_pct:.0f}% replacement"])
    if inp.sf_pct>0:     pr.append(["Silica fume",f"{p['sf_lbs']:.0f}",f"{v['sf']:.3f}",f"{inp.sf_pct:.0f}% replacement"])
    if inp.pcc_pct>0:    pr.append(["PCC (inert micro-filler)",f"{p['pcc_lbs']:.0f}",f"{v['pcc']:.3f}",f"{inp.pcc_pct:.0f}% — particle packing"])
    pr += [
        ["Coarse aggregate (SSD)",f"{p['ca_lbs']:.0f}",f"{v['ca']:.3f}",f"BV of CA = {aci['bv_ca']:.2f}"],
        ["Fine aggregate (SSD)",f"{p['fa_lbs']:.0f}",f"{v['fa']:.3f}","Absolute volume method"],
        ["Air","—",f"{v['air']:.3f}",f"{aci['air_pct']}%"],
        ["TOTAL",f"{total_mass:.0f}",f"{v['total']:.3f}",""],
    ]
    pt2 = Table(pr, colWidths=[2.4*inch,0.9*inch,0.9*inch,2.8*inch])
    pt2.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),TEAL),("TEXTCOLOR",(0,0),(-1,0),WHITE),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
        ("FONTNAME",(0,-1),(-1,-1),"Helvetica-Bold"),
        ("BACKGROUND",(0,-1),(-1,-1),GRAY_LIGHT),
        ("FONTSIZE",(0,0),(-1,-1),8.5),
        ("ROWBACKGROUNDS",(0,1),(-1,-2),[WHITE,GRAY_LIGHT]),
        ("GRID",(0,0),(-1,-1),0.5,BORDER),
        ("ALIGN",(1,0),(2,-1),"RIGHT"),
        ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
        ("LEFTPADDING",(0,0),(-1,-1),8),
        ("TEXTCOLOR",(0,1),(-1,-2),GRAY_DARK),
    ]))
    story += [pt2, Spacer(1,12)]

    # ── Durability flags ──────────────────────────────────────────────────────
    story.append(Paragraph("Durability flags", s_sec))
    flag_rows = [["Status","Flag"]]
    for f in aci["flags"]:
        flag_rows.append(["OK" if f["status"]=="ok" else ("WARN" if f["status"]=="warning" else "CRIT"), f["flag"]])
    ft = Table(flag_rows, colWidths=[0.7*inch, 6.3*inch])
    fstyles = [
        ("BACKGROUND",(0,0),(-1,0),TEAL),("TEXTCOLOR",(0,0),(-1,0),WHITE),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),
        ("FONTSIZE",(0,0),(-1,-1),8.5),
        ("GRID",(0,0),(-1,-1),0.5,BORDER),
        ("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5),
        ("LEFTPADDING",(0,0),(-1,-1),8),
    ]
    for i, f in enumerate(aci["flags"], start=1):
        bg_c = TEAL_LIGHT if f["status"]=="ok" else (AMBER_LIGHT if f["status"]=="warning" else RED_LIGHT)
        fg_c = TEAL if f["status"]=="ok" else (AMBER if f["status"]=="warning" else RED)
        fstyles += [("BACKGROUND",(0,i),(-1,i),bg_c),("TEXTCOLOR",(0,i),(0,i),fg_c),("TEXTCOLOR",(1,i),(1,i),GRAY_DARK)]
    ft.setStyle(TableStyle(fstyles))
    story += [ft, Spacer(1,12)]

    # ── SCM notes, compliance, QC ─────────────────────────────────────────────
    def list_tbl(title, items):
        rows = [[title]] + [[f"- {i}"] for i in (items or ["None"])]
        t = Table(rows, colWidths=[W])
        t.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),TEAL),("TEXTCOLOR",(0,0),(-1,0),WHITE),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
            ("FONTSIZE",(0,0),(-1,-1),8.5),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[WHITE,GRAY_LIGHT]),
            ("GRID",(0,0),(-1,-1),0.5,BORDER),
            ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
            ("LEFTPADDING",(0,0),(-1,-1),8),
            ("TEXTCOLOR",(0,1),(-1,-1),GRAY_DARK),
        ]))
        return t

    story.append(Paragraph("SCM & PCC notes", s_sec))
    story.append(list_tbl("SCM & PCC compatibility notes", result.scm_notes))
    story += [Spacer(1,8)]
    story.append(Paragraph("ACI 211.1 compliance", s_sec))
    story.append(list_tbl("ACI 211.1 compliance notes", result.aci_compliance))
    story += [Spacer(1,8)]
    story.append(Paragraph("Recommended QC tests", s_sec))
    story.append(list_tbl("QC tests", result.qc_tests))
    story += [Spacer(1,10)]

    # ── Recommendations ───────────────────────────────────────────────────────
    if result.recommendations:
        story.append(Paragraph("Recommendations", s_sec))
        rt = Table([[result.recommendations]], colWidths=[W])
        rt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),GRAY_LIGHT),
            ("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8),
            ("LEFTPADDING",(0,0),(-1,-1),10),("GRID",(0,0),(-1,-1),0.5,BORDER),
            ("FONTSIZE",(0,0),(-1,-1),8.5),("TEXTCOLOR",(0,0),(-1,-1),GRAY_DARK)]))
        story += [rt, Spacer(1,8)]

    if inp.field_notes:
        story.append(Paragraph("Field notes", s_sec))
        story.append(Paragraph(inp.field_notes, s_body))
        story.append(Spacer(1,8))

    # ── Footer ────────────────────────────────────────────────────────────────
    story += [
        Spacer(1,10),
        HRFlowable(width=W, thickness=0.5, color=BORDER),
        Spacer(1,5),
        Paragraph(
            "This report was generated by a prototype tool developed by the Teymouri Research Lab, "
            "Dept. of Construction &amp; Concrete Industry Management, Jerome J. Lohr College of Engineering, "
            "South Dakota State University (SDSU). "
            "Calculations follow ACI 211.1 (PCA Method). "
            "This tool provides AI-assisted preliminary mix design guidance only — "
            "not a substitute for a licensed structural engineer or certified concrete technologist. "
            "PCC (Precipitated Calcium Carbonate) is modeled as an inert micro-filler.",
            s_note),
    ]

    doc.build(story)
    return buf.getvalue()
